# Knowledge Extraction Pipeline Configuration

# === Content Filtering Settings ===
filtering:
  enabled: false                      # Master switch (abilita/disabilita tutti i filtri)

  # Pattern-based filtering
  pattern_filtering:
    enabled: true
    skip_patterns:
      - "^table of contents$"
      - "^index$"
      - "warranty"
      - "legal notice"
      - "page \\d+"
      - "^appendix"
      - "^bibliography"
      - "^references$"
    case_sensitive: false            # Ignora maiuscole/minuscole nei pattern
    match_scope: "title"             # Dove applicare i pattern: title, text, both
    max_text_scan_chars: 2000        # Numero max caratteri da esaminare nel testo per match

  # Content quality
  content_quality:
    enabled: true
    min_text_length: 100             # Min caratteri totali richiesti
    max_whitespace_ratio: 0.8        # Scarta se oltre 80% è spazio bianco
    min_non_whitespace_chars: 50     # Min caratteri "significativi"

  # Language detection
  language_detection:
    enabled: true
    target_language: "en"            # Lingua attesa delle sezioni
    min_text_for_detection: 50       # Min caratteri per tentare detection
    confidence_threshold: 0.7        # Soglia confidenza minima accettata
    fallback_on_error: true          # Se detection fallisce, tieni la sezione

  # Structural filtering
  structural_filtering:
    enabled: true
    skip_section_titles:
      - "table of contents"
      - "index"
      - "warranty"
      - "legal notice"
      - "disclaimer"
      - "copyright"
      - "trademark"
    max_chars_per_section: 10000     # Spezza sezioni troppo grandi (soft split)

# === PDF Processing Settings ===
pdf_processing:
  datasource_code: "SRC_DOCS_PIPELINE5"
  default_language: "en"
  skip_start_pages: 1  # Numero di pagine da saltare all'inizio del PDF (per escludere copertine, copyright, ecc)
  skip_end_pages: 1     # Numero di pagine finali da saltare (per escludere appendici inutili, pubblicità, ecc)

# === Output Settings ===
output:
  individual_files: true
  batch_file: false
  indent: 2
  ensure_ascii: false

# === Logging Settings ===
logging:
  level: "INFO"           # (DEBUG, INFO, WARNING, ERROR)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# === Neural Extractor Module ===
neural_extractor:
  enabled: false
  provider: "openai"               # 'openai' or other provider id used by the module
  model: "gpt-4o-mini"             # modello predefinito per il modulo neurale
  api_key_env: "OPENAI_API_KEY"
  temperature: 0.0
  max_output_tokens: 1024
  request_timeout: 60              # timeout (secondi) per le chiamate al modello

# === Pipeline Settings ===
pipelines:
  product_technical:
    enabled: true
    source_dir: "source/product_technical"
    output_dir: "output/partial/product_technical"
    document_glob: "*.pdf"
    symbolic:
      skip_header_footer_patterns:
        footer: "citiz service manual\\s+\\d+$"
        header: "^[A-Z\\s]+\\|$"
        page_number: "^\\s*\\d+\\s*$"
        decoration: "^[\\-|\\s─═]+$"
      section_patterns:
        level1: "^\\d+\\s+[A-Z][A-Z\\s&]+$"
        level2: "^\\d+\\.\\d+\\s+.+$"
        level3: "^\\d+\\.\\d+\\.\\d+\\s+.+$"
      role_heuristics:
        figure_keywords:
          - "diagram"
          - "view"
          - "schematic"
          - "overview"
        table_keywords:
          - "|"
          - "table"
          - "specification"
          - "rating"
        warning_keywords:
          - "warning"
          - "caution"
          - "danger"
          - "note"
          - "important"
      tagging_keywords:
        component_list_pattern: "^\\s*\\d+\\)"
        dimensions:
          - "mm"
          - "kg"
          - "width"
          - "height"
          - "depth"
          - "dimension"
        electrical:
          - "voltage"
          - "hz"
          - "amp"
          - "watt"
          - "v "
        model_codes:
          - "c110"
          - "d120"
          - "c170"
        brand:
          - "delonghi"
          - "krups"
          - "magimix"
          - "nespresso"
      table_detection:
        dotted_leader_threshold: 3
        min_pipe_columns: 3
        min_consistent_rows: 3
        max_separator_variance: 2
      quality_thresholds:
        min_text_coverage: 0.7
      rating_plate:
        enabled: true
        title_keywords:
          - "rating plate"
          - "rating plates"
        brands:
          - "nespresso"
          - "delonghi"
          - "koenig"
          - "krups"
          - "magimix"
          - "turmix"
        region_tokens:
          - "eu"
          - "ch"
          - "at"
          - "us"
          - "uk"
          - "apac"
          - "me"
        default_tags:
          - "rating_plate"
          - "brand_specific"
      implicit_subsections:
        enabled: true
        heading_patterns:
          - "^([A-Z][A-Za-z0-9\\s,&-]+):?$"
          - "^([A-Z][A-Z\\s/&-]+)$"
        max_heading_words: 8
        min_block_chars: 40
      warning_detection:
        enabled: true
        snippet_window: 120
        promote_role_max_chars: 600
        patterns:
          - "(WARNING|CAUTION|DANGER|IMPORTANT|ATTENTION)"
          - "(not compatible|incompatible)"
          - "(do not|never|avoid).{0,50}(mix|combine|use with)"
          - "(must not|cannot be used|will not work)"
          - "^Note:?|^Nota:?"
