# Knowledge Extraction Pipeline Configuration

# === Content Filtering Settings ===
filtering:
  enabled: true                      # Master switch (abilita/disabilita tutti i filtri)

  # Pattern-based filtering
  pattern_filtering:
    enabled: true
    skip_patterns:
      - "^table of contents$"
      - "^index$"
      - "warranty"
      - "legal notice"
      - "page \\d+"
      - "^appendix"
      - "^bibliography"
      - "^references$"
    case_sensitive: false            # Ignora maiuscole/minuscole nei pattern
    match_scope: "title"            # Dove applicare i pattern: title, text, both
    max_text_scan_chars: 2000        # Numero max caratteri da esaminare nel testo per match

  # Content quality
  content_quality:
    enabled: true
    min_text_length: 100             # Min caratteri totali richiesti
    max_whitespace_ratio: 0.8        # Scarta se oltre 80% è spazio bianco
    min_non_whitespace_chars: 50     # Min caratteri "significativi"

  # Language detection
  language_detection:
    enabled: true
    target_language: "en"            # Lingua attesa delle sezioni
    min_text_for_detection: 50       # Min caratteri per tentare detection
    confidence_threshold: 0.7        # Soglia confidenza minima accettata
    fallback_on_error: true          # Se detection fallisce, tieni la sezione

  # Structural filtering
  structural_filtering:
    enabled: true
    skip_section_titles:
      - "table of contents"
      - "index"
      - "warranty"
      - "legal notice"
      - "disclaimer"
      - "copyright"
      - "trademark"
    max_chars_per_section: 10000     # Spezza sezioni troppo grandi (soft split)

# === PDF Processing Settings ===
pdf_processing:
  datasource_code: "SRC_DOCS_PIPELINE5"
  default_language: "en"

# === Output Settings ===
output:
  individual_files: true
  batch_file: false
  indent: 2
  ensure_ascii: false

# === Logging Settings ===
logging:
  level: "INFO"           # (DEBUG, INFO, WARNING, ERROR)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# === Neural Extractor Module ===
neural_extractor:
  enabled: true
  provider: "openai"               # 'openai' or other provider id used by the module
  model: "gpt-4o-mini"             # modello predefinito per il modulo neurale
  api_key_env: "OPENAI_API_KEY"
  temperature: 0.0
  max_output_tokens: 1024
  request_timeout: 60              # timeout (secondi) per le chiamate al modello
